import Head from 'next/head'
import WithHeader from '../../shared/layouts/WithHeader'
import { useDispatch } from 'react-redux'

export default function QuestionsPage() {
  const dispatch = useDispatch()
  return (
    <WithHeader>
      <div>
        <Head>
          <title>Questions</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <div className="mx-auto max-w-7xl px-2 sm:px-4 lg:px-8">Questions</div>

      </div>
    </WithHeader>
  )
}
